# docker-compose.yaml
version: "2"
services:
  WebProxy:
    container_name: WebProxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local
    links:
      - WebApp:webapp
  WebApp:
    container_name: WebApp
    image: candymi/cfweb:latest
    networks:
      - local
networks:
  local:
    driver: bridge
