# docker-compose.yaml
version: "2"
services:
  WebProxy:
    container_name: WebProxy
    image: nginx:latest
    ports:
      - 80:80
      - 8080:81
    volumes:
      - ~/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local
    links:
      - WebApp:webapp
  WebApp:
    container_name: WebApp
    image: candymi/cfweb:latest
    ports:
      - 8080
    networks:
      - local
networks:
  local:
    driver: bridge
